name: Cowstalt
options:
  bundleIdPrefix: com.cowstalt
targets:
  Cowstalt:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Cowstalt
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cowstalt.app
      INFOPLIST_KEY_CFBundleDisplayName: "Cowstalt"
      INFOPLIST_KEY_UIMainStoryboardFile: ""
      INFOPLIST_KEY_UILaunchScreen: {}
