name: Build Cowstalt .ipa

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  build:
    name: Build and Package iOS .ipa
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate .xcodeproj
        run: xcodegen generate

      - name: Build and Archive
        run: |
          xcodebuild -project Cowstalt.xcodeproj \
                     -scheme Cowstalt \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     -archivePath $PWD/build/Cowstalt.xcarchive \
                     archive

      - name: Package into .ipa
        run: |
          mkdir -p Payload
          cp -r build/Cowstalt.xcarchive/Products/Applications/Cowstalt.app Payload/
          zip -r Cowstalt.ipa Payload
          rm -rf Payload

      - name: Upload .ipa Artifact
        uses: actions/upload-artifact@v4
        with:
            name: Cowstalt-ipa
            path: Cowstalt.ipa
