name: Build Cowstalt

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  build:
    name: Build iOS Project
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate .xcodeproj
        run: xcodegen generate

      - name: Build and Archive
        run: |
          xcodebuild -project Cowstalt.xcodeproj \
                     -scheme Cowstalt \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     -archivePath $PWD/build/Cowstalt.xcarchive \
                     archive

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
            name: Cowstalt-Archive
            path: build/Cowstalt.xcarchive
